task: 'retriever'

env:
  num_threads: 16
  seed: 42

dataset:
  name: 'kgqagen'
  text_encoder_name: 'gte-large-en-v1.5'

retriever:
  topic_pe: true
  DDE_kwargs:
    num_rounds: 2
    num_reverse_rounds: 2

# KGE configuration
kge:
  enabled: true
  model_type: 'transe'  # Options: 'transe', 'distmult', 'ptranse', 'rotate', 'complex', 'simple', 'interht'
  embedding_dim: 256
  num_epochs: 100
  batch_size: 1024
  learning_rate: 0.001
  margin: 1.0
  num_negatives: 1
  norm: 1  # For TransE/PTransE
  loss_weight: 1.0  # Weight for KGE margin ranking loss

optimizer:
  lr: 1e-3

eval:
  k_list: '100'

train:
  num_epochs: 10000
  patience: 10
  save_prefix: 'kgqagen' 